version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fc_web
    container_name: fc_web_container
    command: /start.bash
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./project:/project
    ports:
      - 8000:8000
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - db

  db:
    image: postgres:13-alpine
    container_name: fc_postgres_container
    volumes:
      - fc_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fastapi_celery
      - POSTGRES_USER=fastapi_celery
      - POSTGRES_PASSWORD=fastapi_celery

  redis:
    image: redis:6-alpine
    container_name: fc_redis_container


  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fc_celery_worker
    container_name: fc_celery_worker_container
    command: /start-celeryworker.bash
    volumes:
      - ./project:/project
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fc_celery_beat
    container_name: fc_celery_beat_container
    command: /start-celerybeat.bash
    volumes:
      - ./project:/project
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fc_celery_flower
    container_name: fc_celery_flower_container
    command: /start-flower.bash
    volumes:
      - ./project:/project
    env_file:
      - .env/.dev-sample
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

volumes:
  fc_postgres_data:
