"""empty message

Revision ID: 697aa6caaa13
Revises: e8cccb389482
Create Date: 2021-10-20 10:36:12.644848

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "697aa6caaa13"
down_revision = "e8cccb389482"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
